import JSZip from "jszip";
import { UniversalSkill } from "./types";

export function generateSkillProjectFiles(skill: UniversalSkill): Record<string, string> {
  const readmeContent = `# ${skill.title} (Agent Skill)

> Extracted from: ${skill.targetUrl}  
> Generated by **SkillForge Universal URL-to-SKILL.md Engine**

## Files in this Package
- **\`SKILL.md\`**: Canonical agent skill specification with YAML frontmatter. Usable directly in any AI agent system (Antigravity, Cursor, Windsurf, Claude Projects, Gemini Agents).
- **\`Component.tsx\`**: Standalone React + TypeScript + Tailwind CSS component implementing the extracted design tokens and interactive logic.
- **\`gemini-instructions.txt\`**: Copy-paste system instruction prompt for Google Gemini (Google AI Studio / Gemini CLI).
- **\`chatgpt-instructions.txt\`**: Copy-paste instructions for OpenAI ChatGPT Custom GPTs.
- **\`.cursorrules\`**: Ready-to-use Cursor / Windsurf rules file.
- **\`claude-instructions.txt\`**: Project prompt for Anthropic Claude.

---

## How to Use Across Models

### 1. Google Gemini (AI Studio / Gemini CLI)
Paste the contents of \`gemini-instructions.txt\` or \`SKILL.md\` into the **System Instructions** field in Google AI Studio.

### 2. Cursor / Windsurf IDE
Drop \`.cursorrules\` into the root of your project or add \`SKILL.md\` to your project's \`.skills/\` directory.

### 3. OpenAI ChatGPT
In **Explore GPTs -> Create a GPT -> Configure**, paste \`chatgpt-instructions.txt\` into the **Instructions** field.

### 4. Anthropic Claude
Upload \`SKILL.md\` to your **Claude Project Knowledge** or paste into your system instructions.
`;

  return {
    "SKILL.md": skill.skillMd,
    "Component.tsx": skill.componentCode,
    "gemini-instructions.txt": skill.modelPrompts.gemini,
    "chatgpt-instructions.txt": skill.modelPrompts.chatgpt,
    ".cursorrules": skill.modelPrompts.cursor,
    "claude-instructions.txt": skill.modelPrompts.claude,
    "README.md": readmeContent,
  };
}

/**
 * Creates a downloadable .zip archive of the complete multi-model skill package
 */
export async function createSkillZipBundle(skill: UniversalSkill): Promise<Buffer> {
  const files = generateSkillProjectFiles(skill);
  const zip = new JSZip();

  for (const [filename, content] of Object.entries(files)) {
    zip.file(filename, content);
  }

  return await zip.generateAsync({ type: "nodebuffer" });
}
