import JSZip from "jszip";
import { DesignSystemData } from "./types";

export function generateDesignProjectFiles(design: DesignSystemData): Record<string, string> {
  const readmeContent = `# ${design.title} — Design System Package

> Extracted from: ${design.targetUrl}  
> Generated by **DesignMD Engine** (Google Stitch & DesignMD Standard)

## Files in this Package
- **\`DESIGN.md\`**: Canonical plain-Markdown design system specification capturing colors, typography, spacing, elevation, and component rules for humans and AI coding agents.
- **\`tokens.css\`**: Ready-to-use CSS Custom Properties (\`:root { ... }\`) for your stylesheet.
- **\`tailwind.config.js\`**: Tailwind CSS v3 theme extension & Tailwind v4 \`@theme\` configuration.
- **\`tokens.json\`**: W3C Design Tokens Community Group JSON format for Figma / Style Dictionary.
- **\`Specimens.tsx\`**: Standalone React + TypeScript + Tailwind CSS component rendering live interactive buttons, inputs, cards, badges, and color swatches.
- **\`.cursorrules\`**: Ready-to-drop configuration file for Cursor and Windsurf IDEs.
- **\`CLAUDE.md\`**: Project instruction guidelines for Anthropic Claude Code & Claude Projects.
- **\`gemini-prompt.txt\`**: Copy-paste System Instructions for Google Gemini (AI Studio / Gemini API).
- **\`chatgpt-prompt.txt\`**: Copy-paste instructions for OpenAI ChatGPT Custom GPTs.

---

## How to Use with AI Coding Agents

### 1. Cursor & Windsurf
Place \`DESIGN.md\` and \`.cursorrules\` in the root of your project:
\`\`\`bash
cp DESIGN.md /path/to/project/
cp .cursorrules /path/to/project/
\`\`\`
Ask Cursor: *"Build a new dashboard settings page following the tokens in DESIGN.md."*

### 2. Claude Code & Claude Projects
Place \`CLAUDE.md\` and \`DESIGN.md\` in your project root or upload \`DESIGN.md\` to your Claude Project Knowledge:
\`\`\`bash
cp CLAUDE.md /path/to/project/
\`\`\`

### 3. v0 by Vercel & Lovable
Paste \`DESIGN.md\` directly into your initial prompt to guide v0 or Lovable to use these exact colors, fonts, and component styles.

### 4. Google Gemini (Google AI Studio)
Paste the contents of \`gemini-prompt.txt\` or \`DESIGN.md\` into the **System Instructions** field in Google AI Studio.
`;

  return {
    "DESIGN.md": design.designMd || design.skillMd,
    "tokens.css": design.cssVariablesFormatted,
    "tailwind.config.js": design.tailwindConfigFormatted,
    "tokens.json": design.tokensJsonFormatted,
    "Specimens.tsx": design.componentCode,
    ".cursorrules": design.modelPrompts.cursor,
    "CLAUDE.md": design.modelPrompts.claude,
    "gemini-prompt.txt": design.modelPrompts.gemini,
    "chatgpt-prompt.txt": design.modelPrompts.chatgpt,
    "README.md": readmeContent,
  };
}

/**
 * Creates a downloadable .zip archive of the complete design system package
 */
export async function createSkillZipBundle(design: DesignSystemData): Promise<Buffer> {
  const files = generateDesignProjectFiles(design);
  const zip = new JSZip();

  for (const [filename, content] of Object.entries(files)) {
    zip.file(filename, content);
  }

  return await zip.generateAsync({ type: "nodebuffer" });
}
